package resources;


/**
 * Holds resources required for testing
 * @author Smit Pateliya, Pradnya Kandarkar
 */
public class TestResources {
	public static final String issueData = "[\r\n"
			+ "  {\r\n"
			+ "    \"url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2813\",\r\n"
			+ "    \"repository_url\": \"https://api.github.com/repos/TheAlgorithms/Java\",\r\n"
			+ "    \"labels_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2813/labels{/name}\",\r\n"
			+ "    \"comments_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2813/comments\",\r\n"
			+ "    \"events_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2813/events\",\r\n"
			+ "    \"html_url\": \"https://github.com/TheAlgorithms/Java/issues/2813\",\r\n"
			+ "    \"id\": 1046594874,\r\n"
			+ "    \"node_id\": \"I_kwDOA8iXnM4-YcU6\",\r\n"
			+ "    \"number\": 2813,\r\n"
			+ "    \"title\": \"Boundary Fill Algorithm\",\r\n"
			+ "    \"user\": {\r\n"
			+ "      \"login\": \"itsAkshayDubey\",\r\n"
			+ "      \"id\": 38462415,\r\n"
			+ "      \"node_id\": \"MDQ6VXNlcjM4NDYyNDE1\",\r\n"
			+ "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/38462415?v=4\",\r\n"
			+ "      \"gravatar_id\": \"\",\r\n"
			+ "      \"url\": \"https://api.github.com/users/itsAkshayDubey\",\r\n"
			+ "      \"html_url\": \"https://github.com/itsAkshayDubey\",\r\n"
			+ "      \"followers_url\": \"https://api.github.com/users/itsAkshayDubey/followers\",\r\n"
			+ "      \"following_url\": \"https://api.github.com/users/itsAkshayDubey/following{/other_user}\",\r\n"
			+ "      \"gists_url\": \"https://api.github.com/users/itsAkshayDubey/gists{/gist_id}\",\r\n"
			+ "      \"starred_url\": \"https://api.github.com/users/itsAkshayDubey/starred{/owner}{/repo}\",\r\n"
			+ "      \"subscriptions_url\": \"https://api.github.com/users/itsAkshayDubey/subscriptions\",\r\n"
			+ "      \"organizations_url\": \"https://api.github.com/users/itsAkshayDubey/orgs\",\r\n"
			+ "      \"repos_url\": \"https://api.github.com/users/itsAkshayDubey/repos\",\r\n"
			+ "      \"events_url\": \"https://api.github.com/users/itsAkshayDubey/events{/privacy}\",\r\n"
			+ "      \"received_events_url\": \"https://api.github.com/users/itsAkshayDubey/received_events\",\r\n"
			+ "      \"type\": \"User\",\r\n"
			+ "      \"site_admin\": false\r\n"
			+ "    },\r\n"
			+ "    \"labels\": [\r\n"
			+ "\r\n"
			+ "    ],\r\n"
			+ "    \"state\": \"open\",\r\n"
			+ "    \"locked\": false,\r\n"
			+ "    \"assignee\": null,\r\n"
			+ "    \"assignees\": [\r\n"
			+ "\r\n"
			+ "    ],\r\n"
			+ "    \"milestone\": null,\r\n"
			+ "    \"comments\": 0,\r\n"
			+ "    \"created_at\": \"2021-11-06T20:53:16Z\",\r\n"
			+ "    \"updated_at\": \"2021-11-06T20:53:16Z\",\r\n"
			+ "    \"closed_at\": null,\r\n"
			+ "    \"author_association\": \"NONE\",\r\n"
			+ "    \"active_lock_reason\": null,\r\n"
			+ "    \"body\": \"Hi,\\nI have not seen any implementation of [Boundary fill algorithm ](https://en.m.wikipedia.org/wiki/Flood_fill) in this repo. I would like to demonstrate the working of Semaphore.\\nCould you please assign this issue to me?\",\r\n"
			+ "    \"reactions\": {\r\n"
			+ "      \"url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2813/reactions\",\r\n"
			+ "      \"total_count\": 0,\r\n"
			+ "      \"+1\": 0,\r\n"
			+ "      \"-1\": 0,\r\n"
			+ "      \"laugh\": 0,\r\n"
			+ "      \"hooray\": 0,\r\n"
			+ "      \"confused\": 0,\r\n"
			+ "      \"heart\": 0,\r\n"
			+ "      \"rocket\": 0,\r\n"
			+ "      \"eyes\": 0\r\n"
			+ "    },\r\n"
			+ "    \"timeline_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2813/timeline\",\r\n"
			+ "    \"performed_via_github_app\": null\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2812\",\r\n"
			+ "    \"repository_url\": \"https://api.github.com/repos/TheAlgorithms/Java\",\r\n"
			+ "    \"labels_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2812/labels{/name}\",\r\n"
			+ "    \"comments_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2812/comments\",\r\n"
			+ "    \"events_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2812/events\",\r\n"
			+ "    \"html_url\": \"https://github.com/TheAlgorithms/Java/issues/2812\",\r\n"
			+ "    \"id\": 1046594033,\r\n"
			+ "    \"node_id\": \"I_kwDOA8iXnM4-YcHx\",\r\n"
			+ "    \"number\": 2812,\r\n"
			+ "    \"title\": \"Flood Fill Algorithm\",\r\n"
			+ "    \"user\": {\r\n"
			+ "      \"login\": \"itsAkshayDubey\",\r\n"
			+ "      \"id\": 38462415,\r\n"
			+ "      \"node_id\": \"MDQ6VXNlcjM4NDYyNDE1\",\r\n"
			+ "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/38462415?v=4\",\r\n"
			+ "      \"gravatar_id\": \"\",\r\n"
			+ "      \"url\": \"https://api.github.com/users/itsAkshayDubey\",\r\n"
			+ "      \"html_url\": \"https://github.com/itsAkshayDubey\",\r\n"
			+ "      \"followers_url\": \"https://api.github.com/users/itsAkshayDubey/followers\",\r\n"
			+ "      \"following_url\": \"https://api.github.com/users/itsAkshayDubey/following{/other_user}\",\r\n"
			+ "      \"gists_url\": \"https://api.github.com/users/itsAkshayDubey/gists{/gist_id}\",\r\n"
			+ "      \"starred_url\": \"https://api.github.com/users/itsAkshayDubey/starred{/owner}{/repo}\",\r\n"
			+ "      \"subscriptions_url\": \"https://api.github.com/users/itsAkshayDubey/subscriptions\",\r\n"
			+ "      \"organizations_url\": \"https://api.github.com/users/itsAkshayDubey/orgs\",\r\n"
			+ "      \"repos_url\": \"https://api.github.com/users/itsAkshayDubey/repos\",\r\n"
			+ "      \"events_url\": \"https://api.github.com/users/itsAkshayDubey/events{/privacy}\",\r\n"
			+ "      \"received_events_url\": \"https://api.github.com/users/itsAkshayDubey/received_events\",\r\n"
			+ "      \"type\": \"User\",\r\n"
			+ "      \"site_admin\": false\r\n"
			+ "    },\r\n"
			+ "    \"labels\": [\r\n"
			+ "\r\n"
			+ "    ],\r\n"
			+ "    \"state\": \"open\",\r\n"
			+ "    \"locked\": false,\r\n"
			+ "    \"assignee\": null,\r\n"
			+ "    \"assignees\": [\r\n"
			+ "\r\n"
			+ "    ],\r\n"
			+ "    \"milestone\": null,\r\n"
			+ "    \"comments\": 0,\r\n"
			+ "    \"created_at\": \"2021-11-06T20:48:26Z\",\r\n"
			+ "    \"updated_at\": \"2021-11-06T20:50:22Z\",\r\n"
			+ "    \"closed_at\": null,\r\n"
			+ "    \"author_association\": \"NONE\",\r\n"
			+ "    \"active_lock_reason\": null,\r\n"
			+ "    \"body\": \"Hi,\\nI have not seen any implementation of [Flood Fill Algorithm ](https://en.m.wikipedia.org/wiki/Flood_fill)in this repo. I would like to demonstrate the working of Semaphore.\\nCould you please assign this issue to me?\",\r\n"
			+ "    \"reactions\": {\r\n"
			+ "      \"url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2812/reactions\",\r\n"
			+ "      \"total_count\": 0,\r\n"
			+ "      \"+1\": 0,\r\n"
			+ "      \"-1\": 0,\r\n"
			+ "      \"laugh\": 0,\r\n"
			+ "      \"hooray\": 0,\r\n"
			+ "      \"confused\": 0,\r\n"
			+ "      \"heart\": 0,\r\n"
			+ "      \"rocket\": 0,\r\n"
			+ "      \"eyes\": 0\r\n"
			+ "    },\r\n"
			+ "    \"timeline_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2812/timeline\",\r\n"
			+ "    \"performed_via_github_app\": null\r\n"
			+ "  },\r\n"
			+ "  {\r\n"
			+ "    \"url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2811\",\r\n"
			+ "    \"repository_url\": \"https://api.github.com/repos/TheAlgorithms/Java\",\r\n"
			+ "    \"labels_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2811/labels{/name}\",\r\n"
			+ "    \"comments_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2811/comments\",\r\n"
			+ "    \"events_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2811/events\",\r\n"
			+ "    \"html_url\": \"https://github.com/TheAlgorithms/Java/pull/2811\",\r\n"
			+ "    \"id\": 1045844195,\r\n"
			+ "    \"node_id\": \"PR_kwDOA8iXnM4uJgGp\",\r\n"
			+ "    \"number\": 2811,\r\n"
			+ "    \"title\": \"Added code\",\r\n"
			+ "    \"user\": {\r\n"
			+ "      \"login\": \"Yukti-DD\",\r\n"
			+ "      \"id\": 84984749,\r\n"
			+ "      \"node_id\": \"MDQ6VXNlcjg0OTg0NzQ5\",\r\n"
			+ "      \"avatar_url\": \"https://avatars.githubusercontent.com/u/84984749?v=4\",\r\n"
			+ "      \"gravatar_id\": \"\",\r\n"
			+ "      \"url\": \"https://api.github.com/users/Yukti-DD\",\r\n"
			+ "      \"html_url\": \"https://github.com/Yukti-DD\",\r\n"
			+ "      \"followers_url\": \"https://api.github.com/users/Yukti-DD/followers\",\r\n"
			+ "      \"following_url\": \"https://api.github.com/users/Yukti-DD/following{/other_user}\",\r\n"
			+ "      \"gists_url\": \"https://api.github.com/users/Yukti-DD/gists{/gist_id}\",\r\n"
			+ "      \"starred_url\": \"https://api.github.com/users/Yukti-DD/starred{/owner}{/repo}\",\r\n"
			+ "      \"subscriptions_url\": \"https://api.github.com/users/Yukti-DD/subscriptions\",\r\n"
			+ "      \"organizations_url\": \"https://api.github.com/users/Yukti-DD/orgs\",\r\n"
			+ "      \"repos_url\": \"https://api.github.com/users/Yukti-DD/repos\",\r\n"
			+ "      \"events_url\": \"https://api.github.com/users/Yukti-DD/events{/privacy}\",\r\n"
			+ "      \"received_events_url\": \"https://api.github.com/users/Yukti-DD/received_events\",\r\n"
			+ "      \"type\": \"User\",\r\n"
			+ "      \"site_admin\": false\r\n"
			+ "    },\r\n"
			+ "    \"labels\": [\r\n"
			+ "\r\n"
			+ "    ],\r\n"
			+ "    \"state\": \"open\",\r\n"
			+ "    \"locked\": false,\r\n"
			+ "    \"assignee\": null,\r\n"
			+ "    \"assignees\": [\r\n"
			+ "\r\n"
			+ "    ],\r\n"
			+ "    \"milestone\": null,\r\n"
			+ "    \"comments\": 0,\r\n"
			+ "    \"created_at\": \"2021-11-05T13:22:43Z\",\r\n"
			+ "    \"updated_at\": \"2021-11-07T15:41:45Z\",\r\n"
			+ "    \"closed_at\": null,\r\n"
			+ "    \"author_association\": \"NONE\",\r\n"
			+ "    \"active_lock_reason\": null,\r\n"
			+ "    \"pull_request\": {\r\n"
			+ "      \"url\": \"https://api.github.com/repos/TheAlgorithms/Java/pulls/2811\",\r\n"
			+ "      \"html_url\": \"https://github.com/TheAlgorithms/Java/pull/2811\",\r\n"
			+ "      \"diff_url\": \"https://github.com/TheAlgorithms/Java/pull/2811.diff\",\r\n"
			+ "      \"patch_url\": \"https://github.com/TheAlgorithms/Java/pull/2811.patch\"\r\n"
			+ "    },\r\n"
			+ "    \"body\": \"### **Describe your change:**\\r\\n\\r\\n- [x] Add an algorithm?\\r\\n- [ ] Fix a bug or typo in an existing algorithm?\\r\\n- [ ] Documentation change?\\r\\n\\r\\n#### References\\r\\n\\r\\n<!-- Add any reference to previous pull-request or issue -->\\r\\n\\r\\n### **Checklist:**\\r\\n\\r\\n<!-- Remove items that do not apply. For completed items, change [ ] to [x]. -->\\r\\n\\r\\n- [x] I have read [CONTRIBUTING.md](https://github.com/TheAlgorithms/Java/blob/master/CONTRIBUTING.md).\\r\\n- [x] This pull request is all my own work -- I have not plagiarized.\\r\\n- [x] I know that pull requests will not be merged if they fail the automated tests.\\r\\n- [x] This PR only changes one algorithm file. To ease review, please open separate PRs for separate algorithms.\\r\\n- [x] All new Java files are placed inside an existing directory.\\r\\n- [x] All filenames are in all uppercase characters with no spaces or dashes.\\r\\n- [x] All functions and variable names follow Java naming conventions.\\r\\n- [x] All new algorithms have a URL in its comments that points to Wikipedia or other similar explanation.\\r\\n- [x] If this pull request resolves one or more open issues then the commit message contains `Fixes: #{$ISSUE_NO}`.\\r\\n\",\r\n"
			+ "    \"reactions\": {\r\n"
			+ "      \"url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2811/reactions\",\r\n"
			+ "      \"total_count\": 0,\r\n"
			+ "      \"+1\": 0,\r\n"
			+ "      \"-1\": 0,\r\n"
			+ "      \"laugh\": 0,\r\n"
			+ "      \"hooray\": 0,\r\n"
			+ "      \"confused\": 0,\r\n"
			+ "      \"heart\": 0,\r\n"
			+ "      \"rocket\": 0,\r\n"
			+ "      \"eyes\": 0\r\n"
			+ "    },\r\n"
			+ "    \"timeline_url\": \"https://api.github.com/repos/TheAlgorithms/Java/issues/2811/timeline\",\r\n"
			+ "    \"performed_via_github_app\": null\r\n"
			+ "  }]";

	public static final String sampleUserProfile = "{\n" +
			"  \"login\": \"pradnya-git-dev\",\n" +
			"  \"id\": 20405400,\n" +
			"  \"node_id\": \"MDQ6VXNlcjIwNDA1NDAw\",\n" +
			"  \"avatar_url\": \"https://avatars.githubusercontent.com/u/20405400?v=4\",\n" +
			"  \"gravatar_id\": \"\",\n" +
			"  \"url\": \"https://api.github.com/users/pradnya-git-dev\",\n" +
			"  \"html_url\": \"https://github.com/pradnya-git-dev\",\n" +
			"  \"followers_url\": \"https://api.github.com/users/pradnya-git-dev/followers\",\n" +
			"  \"following_url\": \"https://api.github.com/users/pradnya-git-dev/following{/other_user}\",\n" +
			"  \"gists_url\": \"https://api.github.com/users/pradnya-git-dev/gists{/gist_id}\",\n" +
			"  \"starred_url\": \"https://api.github.com/users/pradnya-git-dev/starred{/owner}{/repo}\",\n" +
			"  \"subscriptions_url\": \"https://api.github.com/users/pradnya-git-dev/subscriptions\",\n" +
			"  \"organizations_url\": \"https://api.github.com/users/pradnya-git-dev/orgs\",\n" +
			"  \"repos_url\": \"https://api.github.com/users/pradnya-git-dev/repos\",\n" +
			"  \"events_url\": \"https://api.github.com/users/pradnya-git-dev/events{/privacy}\",\n" +
			"  \"received_events_url\": \"https://api.github.com/users/pradnya-git-dev/received_events\",\n" +
			"  \"type\": \"User\",\n" +
			"  \"site_admin\": false,\n" +
			"  \"name\": null,\n" +
			"  \"company\": null,\n" +
			"  \"blog\": \"\",\n" +
			"  \"location\": null,\n" +
			"  \"email\": null,\n" +
			"  \"hireable\": null,\n" +
			"  \"bio\": null,\n" +
			"  \"twitter_username\": null,\n" +
			"  \"public_repos\": 2,\n" +
			"  \"public_gists\": 0,\n" +
			"  \"followers\": 0,\n" +
			"  \"following\": 0,\n" +
			"  \"created_at\": \"2016-07-11T18:26:26Z\",\n" +
			"  \"updated_at\": \"2021-11-04T15:44:54Z\"\n" +
			"}";
}
